/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace HabitRegistry {
  export type HabitRecordStruct = {
    user: AddressLike;
    habitType: string;
    timestamp: BigNumberish;
    metadataUri: string;
  };

  export type HabitRecordStructOutput = [
    user: string,
    habitType: string,
    timestamp: bigint,
    metadataUri: string
  ] & {
    user: string;
    habitType: string;
    timestamp: bigint;
    metadataUri: string;
  };
}

export interface HabitRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminRecordHabitForUser"
      | "getRecord"
      | "getUserRecordCount"
      | "getUserRecords"
      | "owner"
      | "recordHabit"
      | "records"
      | "renounceOwnership"
      | "transferOwnership"
      | "userRecords"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "HabitRecorded" | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminRecordHabitForUser",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordHabit",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "records",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRecords",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminRecordHabitForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordHabit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "records", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userRecords",
    data: BytesLike
  ): Result;
}

export namespace HabitRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    habitType: string
  ];
  export type OutputTuple = [id: bigint, user: string, habitType: string];
  export interface OutputObject {
    id: bigint;
    user: string;
    habitType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HabitRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): HabitRegistry;
  waitForDeployment(): Promise<this>;

  interface: HabitRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminRecordHabitForUser: TypedContractMethod<
    [targetUser: AddressLike, habitType: string, metadataUri: string],
    [void],
    "nonpayable"
  >;

  getRecord: TypedContractMethod<
    [id: BigNumberish],
    [HabitRegistry.HabitRecordStructOutput],
    "view"
  >;

  getUserRecordCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserRecords: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordHabit: TypedContractMethod<
    [habitType: string, metadataUri: string],
    [void],
    "nonpayable"
  >;

  records: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        habitType: string;
        timestamp: bigint;
        metadataUri: string;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminRecordHabitForUser"
  ): TypedContractMethod<
    [targetUser: AddressLike, habitType: string, metadataUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecord"
  ): TypedContractMethod<
    [id: BigNumberish],
    [HabitRegistry.HabitRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRecordCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRecords"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordHabit"
  ): TypedContractMethod<
    [habitType: string, metadataUri: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "records"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        user: string;
        habitType: string;
        timestamp: bigint;
        metadataUri: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "HabitRecorded"
  ): TypedContractEvent<
    HabitRecordedEvent.InputTuple,
    HabitRecordedEvent.OutputTuple,
    HabitRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "HabitRecorded(uint256,address,string)": TypedContractEvent<
      HabitRecordedEvent.InputTuple,
      HabitRecordedEvent.OutputTuple,
      HabitRecordedEvent.OutputObject
    >;
    HabitRecorded: TypedContractEvent<
      HabitRecordedEvent.InputTuple,
      HabitRecordedEvent.OutputTuple,
      HabitRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
